import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const livvic = Poppins({
  weight: ['100', '300', '400', '700'],
  subsets: ['latin'],
  style: ['normal', 'italic']
 })

export const metadata: Metadata = {
  title: "The Gʊd Aɪ’diə Company",
  description: "Generated by Net-Trix Solutions",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${livvic.className} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
